### ISSUE TITLE
Littlewigs missing Shadowlands De Other Side encounter abilities

### ISSUE THREAD

**Issue by taoriux** [BigWigsMods/LittleWigs#540]
Hello, 
**Detail of Issue**
Currently Littlewigs is missing Shadowlands De Other Side encounter abilities for all 4 listed bosses.

**To reproduce**
Open BigWigs UI, Click on Dungeon Bosses tab, Choose De Other Side from Shadowlands drop menu. No encounter abilities appear under all of 4 listed bosses.

**Current version of game and addon**
BgWigs v188.1
Littlewigs v9.0.6
Game client 9.0.2 Nov 24 2020

**Comment by Diablolock** [comment]
Same issue.

**Comment by funkydude** [comment]
Fixed next release, thanks.

**Comment by domi1294** [comment]
I believe the timer for P2 on the Mueh'zala encounter is still missing (https://www.wowhead.com/spell=334970/coalescing), it doesn't list the ability anywhere at least

**Comment by Justw8** [comment]
Added. Thanks!
